[LIVY-968][SERVER] Provide ttl field for a livy session
apache/incubator-livy pull request #384
Opened 2023-01-23 11:45 UTC by askhatri

## What changes were proposed in this pull request?

A session should have a field 'ttl' (Time to live) which once exceeded should get the session killed.This field can be a parameter in the POST /sessions request and then be a part of session object. Livy has a config `livy.server.session.timeout` but this is a global config and cannot be configured for a session. A 'ttl' field can help set this for a session level.

JIRA: https://issues.apache.org/jira/browse/LIVY-968

## How was this patch tested?

Verified manually by creating interactive session via REST API call in a local Yarn cluster. Also, we have add the new unit tests.

2023-01-25 17:04 UTC, gyogal commented on server/src/main/scala/org/apache/livy/sessions/SessionManager.scala
> +              ClientConf.getTimeAsNanos(session.ttl.orNull, session.id, sessionTimeout)
The TTL string is currently only validated here. If the formatting is invalid it seems like this will keep logging error messages every time `expired()` is called. To prevent this, the string could be validated as the session in created.

2023-01-28 02:34 UTC, ksumit requested changes
Overall looks good, not clear on when a nanosecond level of ttl will be useful for a session, my recommendation would to be to keep it at minutes but i'm ok with seconds too.

2023-01-28 02:34 UTC, ksumit commented on client-common/src/main/java/org/apache/livy/client/common/ClientConf.java
> +  protected static Logger LOG = LoggerFactory.getLogger(ClientConf.class);
should this be final too?

2023-01-28 02:34 UTC, ksumit commented on server/src/main/scala/org/apache/livy/sessions/SessionManager.scala
> +            val calculatedTimeout =
nanoseconds seems too much to me, from my exposure to customer usecases i think ttl in minutes should be enough. curious to know when nanoseconds level of granularity would be useful.

please consider simplifying this further by making this an `Int` or `Long` and avoiding all the parsing and validation logic. for the variable naming, what do you think of `ttlInMinutes` or `ttlInSeconds`?

2023-01-28 02:34 UTC, ksumit commented on docs/rest-api.md
> +    <td>The timeout for this inactive session</td>
would be useful to provide some examples here.

`timeout for this inactive session in minutes/seconds, example: 10`

2023-01-28 02:34 UTC, ksumit commented on server/src/main/scala/org/apache/livy/sessions/Session.scala
> +    val ttl: Option[String],
should we add an auxiliary constructor as well that matches the existing constructor (4 parameters only) and takes the global session timeout as ttl by default? this will help reduce the amount of change in this PR.

2023-01-28 04:18 UTC, askhatri commented on client-common/src/main/java/org/apache/livy/client/common/ClientConf.java
> +  protected static Logger LOG = LoggerFactory.getLogger(ClientConf.class);
Sure @ksumit , I will try to make it final

2023-01-28 04:21 UTC, askhatri commented on server/src/main/scala/org/apache/livy/sessions/SessionManager.scala
> +            val calculatedTimeout =
nanoseconds logic is only for internal calculation and `System.nanoTime()` is an existing code. End user has option to provide the value like "30s" for 30 seconds and "2m" for 2 minutes.

2023-01-28 04:22 UTC, askhatri commented on docs/rest-api.md
> +    <td>The timeout for this inactive session</td>
Sure @ksumit , I will try to update this note.

2023-01-28 04:24 UTC, askhatri commented on server/src/main/scala/org/apache/livy/sessions/Session.scala
> +    val ttl: Option[String],
Sure @ksumit , I will check the possibility to add a auxiliary constructor.

2023-01-28 19:11 UTC, ksumit commented on server/src/main/scala/org/apache/livy/sessions/SessionManager.scala
> +            val calculatedTimeout =
hi @askhatri, i should have been more specific, i had following specific concerns:
1. the logic on parsing the string and converting it to seconds, milliseconds etc seems more complex. instead i was proposing that we use `Int` or `Long` and use number to denote the ttl value
2. fix the granularity for ttl either in minutes or seconds to avoid the complexity
3. depending on whether we fix it in minutes or seconds to be very explicit, name the variable as `ttlInMinutes` or `ttlInSeconds`

2023-02-01 04:26 UTC, askhatri commented on server/src/main/scala/org/apache/livy/sessions/SessionManager.scala
> +            val calculatedTimeout =
I got it @ksumit . So presently we have three options now:
1) Use "ttl" with "String" datatype and keep parsing logic same as global config.
2) Change filed name to "ttlInMinutes" with "Int" datatype and support only minutes in user inputs.
3) Change filed name to "ttlInSeconds" with "Int" datatype and support only seconds in user inputs.

Since the logic to parse string already and it is consistent with global configuration we are planing to go with option 1. i.e. using "ttl" field as "String".

2023-02-01 20:32 UTC, ksumit requested changes

2023-02-01 20:32 UTC, ksumit commented on server/src/main/scala/org/apache/livy/sessions/SessionManager.scala
> +            val calculatedTimeout =
I see now that global configuration is also using this complicated logic. Thanks for pointing that out. I also noticed that there are bunch of other configurations that follow this same logic. So we can leave this as it is. I'm concerned about duplicate code logic in `getTimeAsMs()` and `getTimeAsNanos()`, please see if we can avoid the same or reuse what's already there?

2023-02-01 20:32 UTC, ksumit commented on client-common/src/main/java/org/apache/livy/client/common/ClientConf.java
> +  public static long getTimeAsNanos(String time, int sessionId, long defaultVale) {
What is your opinion in reusing `getTimeAsMs()` instead of creating a new one? Other than the granularity, do you see any other gap between `getTimeAsMs()` and `getTimeAsNanos()` implementations?

2023-02-01 20:32 UTC, ksumit commented on server/src/main/scala/org/apache/livy/server/interactive/InteractiveSessionServlet.scala
> +      null
should this be considered an error case instead and we throw an appropriate error message here? Or could we log the failure and use the global ttl value in this case as the default value?

2023-02-01 20:32 UTC, ksumit commented on client-common/src/main/java/org/apache/livy/client/common/ClientConf.java
> +  public static boolean validateTtl(String ttl) {
Looks like `validateTtl()` and `getTimeAsNanos()` are using a lot of duplicate code, could we avoid this?

2023-02-01 20:32 UTC, ksumit commented on client-common/src/main/java/org/apache/livy/client/common/HttpMessages.java
>      public SessionInfo(int id, String name, String appId, String owner, String proxyUser,
given that ttl is optional field, should we create an override constructor without this parameter? that way you will be able to avoid other changes in test classes.

2023-02-01 20:32 UTC, ksumit commented on server/src/main/scala/org/apache/livy/server/SessionServlet.scala
> +          BadRequest(ResponseMessage("Rejected, invalid value for ttl field!"))
should we throw an exception in `createSession()` and use appropriate message from that to return the `ResponseMessage` here? There could potentially be other reasons on why `createSession()` could return null, right?

2023-02-01 20:32 UTC, ksumit commented on server/src/main/scala/org/apache/livy/server/interactive/CreateInteractiveRequest.scala
> +      (if (ttl.isDefined) s"driverMemory: ${ttl.get}]" else "]")
typo: we need `ttl` instead of `driverMemory`

2023-02-02 07:17 UTC, askhatri commented on server/src/main/scala/org/apache/livy/server/interactive/InteractiveSessionServlet.scala
> +      null
I have fixed this by adding logic to throw an error.

2023-02-02 07:18 UTC, askhatri commented on client-common/src/main/java/org/apache/livy/client/common/ClientConf.java
> +  public static boolean validateTtl(String ttl) {
Added the logic to reuse the same method.

2023-02-02 07:20 UTC, askhatri commented on client-common/src/main/java/org/apache/livy/client/common/HttpMessages.java
>      public SessionInfo(int id, String name, String appId, String owner, String proxyUser,
This constructor is not used in test classes and it is only one place in InteractiveSessionServlet.scala so we can skip adding extra constructor I believe.

2023-02-02 07:21 UTC, askhatri commented on server/src/main/scala/org/apache/livy/server/SessionServlet.scala
> +          BadRequest(ResponseMessage("Rejected, invalid value for ttl field!"))
I have updated the code to avoid returning null.

2023-02-02 07:21 UTC, askhatri commented on server/src/main/scala/org/apache/livy/server/interactive/CreateInteractiveRequest.scala
> +      (if (ttl.isDefined) s"driverMemory: ${ttl.get}]" else "]")
Done

2023-02-02 07:23 UTC, askhatri commented on client-common/src/main/java/org/apache/livy/client/common/ClientConf.java
> +  public static long getTimeAsNanos(String time, int sessionId, long defaultVale) {
`getTimeAsMs()` is defined at class level as non-static method whereas `getTimeAsNanos()` is a static method. It not easy to reuse I believe.

2023-02-06 11:53 UTC, askhatri commented
Hi @ksumit , most of the changes are completed. Could you please check if we are good to merge it?
CC: @gyogal

2023-02-06 11:53 UTC, askhatri commented on server/src/main/scala/org/apache/livy/sessions/SessionManager.scala
> +              ClientConf.getTimeAsNanos(session.ttl.orNull, session.id, sessionTimeout)
I have completed this code changes.

2023-02-06 20:11 UTC, ksumit requested changes
I'm still concerned about duplicate code in `getTimeAsNanos()`. I've suggested one way to reuse that code. Please consider @gyogal's feedback on parsing and using the correct ttl at the session creation time, there are some minor comments on how we are using a get method to do validation as side effect as well, it's confusing.

2023-02-06 20:11 UTC, ksumit commented on server/src/main/scala/org/apache/livy/server/interactive/InteractiveSessionServlet.scala
> +    ClientConf.getTimeAsNanos(createRequest.ttl.orNull, sessionId, 0L);
this could be place for us to parse and set the ttl value correctly:
1. if it's present and valid, parse it and set to the parsed value
2. if it's invalid, set it to the global session timeout value or reject the request.

This method call is doing the same thing but passing 0L as default value seems hacky/confusing to me. Also calling a get method in isolation without using the return value seems hacky/confusing to me.

2023-02-07 12:38 UTC, askhatri commented on server/src/main/scala/org/apache/livy/sessions/SessionManager.scala
> +              ClientConf.getTimeAsNanos(session.ttl.orNull, session.id, sessionTimeout)
Considering the support for session recovery, we have decided to avoid converting it into long value during session creation.

2023-02-07 12:39 UTC, askhatri commented on client-common/src/main/java/org/apache/livy/client/common/ClientConf.java
> +  public static long getTimeAsNanos(String time, int sessionId, long defaultVale) {
I have updated the code to avoid the code duplication.

2023-02-07 15:06 UTC, askhatri commented
Hi @ksumit , today I have updated the code for further review. 😊
CC: @gyogal

2023-02-08 03:17 UTC, ksumit requested changes
Minor comments, looks good otherwise. Please fix them and i will approve from my side. Thank you for your contribution @askhatri

2023-02-08 03:17 UTC, ksumit commented on server/src/main/scala/org/apache/livy/server/SessionServlet.scala
> +            BadRequest(ResponseMessage("Rejected, Invalid ttl field: " + e.getMessage))
Right now, the message may be related to ttl field validation but this doesn't have to be right? Can we do this instead please?

```
BadRequest(ResponseMessage("Rejected, Reason: " + e.getMessage))
```

2023-02-08 03:17 UTC, ksumit commented on server/src/main/scala/org/apache/livy/server/interactive/InteractiveSessionServlet.scala
> +      ClientConf.getTimeAsMs(createRequest.ttl.orNull);
we don't need to do `orNull` here right?

2023-02-08 03:17 UTC, ksumit commented on server/src/main/scala/org/apache/livy/sessions/SessionManager.scala
> +              calculatedTimeout = ClientConf.getTimeAsMs(session.ttl.orNull)
we don't need `orNull` here right?

2023-02-08 05:20 UTC, askhatri commented on server/src/main/scala/org/apache/livy/sessions/SessionManager.scala
> +              calculatedTimeout = ClientConf.getTimeAsMs(session.ttl.orNull)
I have removed `orNull`.

2023-02-08 05:20 UTC, askhatri commented on server/src/main/scala/org/apache/livy/server/interactive/InteractiveSessionServlet.scala
> +      ClientConf.getTimeAsMs(createRequest.ttl.orNull);
I have removed `orNull`.

2023-02-08 05:21 UTC, askhatri commented on server/src/main/scala/org/apache/livy/server/SessionServlet.scala
> +            BadRequest(ResponseMessage("Rejected, Invalid ttl field: " + e.getMessage))
I have updated the code as requested.

2023-02-08 14:22 UTC, askhatri commented
> Minor comments, looks good otherwise. Please fix them and i will approve from my side. Thank you for your contribution @askhatri

All comments fixed today as suggested by you.

2023-02-08 17:55 UTC, ksumit approved these changes
LGTM, +1

2023-02-09 09:32 UTC, gyogal commented
This looks good to me as well. Thinking about it, it may be good to introduce a maximum or a limit for this, so that it cannot be longer than a set amount. But this could be addressed in a separate ticket.

2023-02-09 09:42 UTC, gyogal approved these changes

2023-02-10 16:12 UTC, merged